[[constraint]]
  branch = "master"
  name = "github.com/99designs/gqlgen"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  branch = "master"
  name = "github.com/vektah/gqlparser"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.18.0"

[prune]
  go-tests = true
  unused-packages = true
