version: 2
jobs:
  build:
    docker:
    - image: golang:1.9
    working_directory: /go/src/github.com/99designs/gqlgen-contrib
    steps:
    - checkout
    - run: go get -u github.com/alecthomas/gometalinter github.com/vektah/gorunpkg && gometalinter --install
    - run: go generate ./... && if [[ $(git --no-pager diff) ]] ; then echo "you need to run go generate" ; git --no-pager diff ; exit 1 ; fi
    - run: go test -race ./...
    - run: gometalinter --vendor ./...
